---
- name: Create Docker Image from Git Repository
  hosts: app_servers
  become: true
  vars:
    git_repo_url: "https://github.com/smitwaman/ansible.git"

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ git_repo_url }}"
          dockerfile: "{{ git_repo_url }}/Dockerfile"
        name: chatgpt
        tag: latest
