---
- name: Create Docker Image from Git Repository
  hosts: app_servers
  become: true
  vars:
    git_repo_url: "https://github.com/smitwaman/ansible.git"
    git_repo_path: "/home/ubuntu/sparx900/ansible/"
  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        clone: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ git_repo_path }}"
          dockerfile: "{{ git_repo_path }}/Dockerfile"
        name: chatgpt
        tag: latest

     - name: Run Docker container
       docker_container:
        name: chatgpt_container
        image: chatgpt:latest
        state: started
        restart_policy: always
        ports:
          - "8082:8082"
