---
- name: Create Docker Image from Git Repository
  hosts: your_host_server
  become: true
  vars:
    git_repo_url: "https://github.com/smitwaman/ansible.git"
    git_repo_path: "smitwaman/ansible.git"
    target_dir: "/home/sparx900/chatgpt"
  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        clone: yes

    - name: Copy necessary files to target directory
      copy:
        src: "{{ git_repo_path }}/path/to/necessary/files"
        dest: "{{ target_dir }}"
        remote_src: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ target_dir }}"
          dockerfile: "{{ target_dir }}/Dockerfile"
        name: chatgpt
        tag: latest
