resource_group_name = "az-900"
virtual_network_name = "az-network"
virtual_network_address_space = ["10.0.0.0/16"]
subnet_name = "az-subnet"
subnet_address_prefixes = ["10.0.1.0/24"]
public_ip_name = "az-publicip"
nsg_name = "az-nsg"
network_interface_name = "az-nic"
ip_configuration_name = "internal"
vm_name = "ansible-demo"
vm_size = "Standard B1s"
vm_admin_username = "adminuser"
ssh_public_key_path = "/path/to/your/ssh/public/key.pub"
