---
- name: Install necessary tools on the app server
  hosts: app_servers
  become: yes
  tasks:
    - name: Update apt package cache (for Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Java
      package:
        name: default-jdk
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Java (OpenJDK) for CentOS
      package:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Maven
      package:
        name: maven
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker (CentOS)
      yum:
        name: docker
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install pip3 (CentOS)
      yum:
        name: python3-pip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
