---
- name: Deploy Spring Boot app in Docker container
  hosts: docker_host
  become: yes
  vars:
    spring_boot_app_name: "spring-boot-app"
    docker_image_name: "spring-boot-app:latest"
    docker_container_name: "spring-boot"
    app_port: 8080

  tasks:
    

    - name: Run Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:{{ app_port }}"
