---
- name: Create Docker Image and Deploy Locally
  hosts: app_servers
  become: true
  vars:
    source_dir: /mnt/c/Users/Sparx/Documents/chatgpt-html
    target_dir: /home/sparx900/chatgpt
  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ target_dir }}"
        state: directory

    - name: Copy all files to target directory
      synchronize:
        src: "{{ source_dir }}/"
        dest: "{{ target_dir }}/"
        mode: pull

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ target_dir }}"
          dockerfile: Dockerfile
        name: chatgpt
        tag: latest

    - name: Run Docker container
      docker_container:
        name: chatgpt_container
        image: chatgpt:latest
        state: started
        restart_policy: always
        ports:
          - "8082:8082"
